# This is a Docker Compose configuration
# intended for development purposes only

version: '3'

volumes:
    db: {}

services:
    db:
        image: mysql:8
        environment:
            MYSQL_DATABASE: moneypenny-dev
            MYSQL_USER: moneypenny-test
            MYSQL_PASSWORD: moneypenny-test
            MYSQL_RANDOM_ROOT_PASSWORD: 'true'
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./dev/docker/init.db:/docker-entrypoint-initdb.d
            - db:/var/lib/mysql
    app:
        build:
            context: .
            dockerfile: ./dev/docker/Dockerfile
        environment:
            APP_URL: http://localhost:${DEV_PORT:-8080}
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: moneypenny-dev
            DB_USERNAME: moneypenny-test
            DB_PASSWORD: moneypenny-test
            TEST_DATABASE_URL: mysql://moneypenny-test:moneypenny-test@db/moneypenny-test
            MAIL_DRIVER: smtp
            MAIL_HOST: mailhog
            MAIL_PORT: 1025
        ports:
            - ${DEV_PORT:-8080}:80
        volumes:
            - ./:/app
            - ./dev/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        entrypoint: /app/dev/docker/entrypoint.app.sh
        extra_hosts:
            - "host.docker.internal:host-gateway"
    node:
        image: node:alpine
        working_dir: /app
        user: node
        volumes:
            - ./:/app
        entrypoint: /app/dev/docker/entrypoint.node.sh
    mailhog:
        image: mailhog/mailhog
        ports:
            - ${DEV_MAIL_PORT:-8025}:8025
