server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;

    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include        fastcgi_params;
        fastcgi_pass   app:9000;
        fastcgi_param  SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param  DOCUMENT_ROOT  $realpath_root;
        fastcgi_index  index.php;

        # Nic nie może chować Set-Cookie:
        # proxy_hide_header Set-Cookie;         # <-- NIE używać
        # fastcgi_ignore_headers Set-Cookie;    # <-- NIE używać
    }

    location ~* \.(?:ico|css|js|gif|jpe?g|png|webp|svg|woff2?)$ {
        try_files $uri =404;
        expires 1M;
        access_log off;
    }
}
