name: PHP Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php: ['8.2']
    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: gd, mbstring, json, curl, xml, mysql, ldap, gmp

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer packages
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Start Database
        run: |
          sudo systemctl start mysql

      - name: Setup Database
        run: |
          mysql -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS `moneypenny-test`;'
          mysql -uroot -proot -e "CREATE USER 'moneypenny-test'@'localhost' IDENTIFIED WITH mysql_native_password BY 'moneypenny-test';"
          mysql -uroot -proot -e "GRANT ALL ON \`moneypenny-test\`.* TO 'moneypenny-test'@'localhost';"
          mysql -uroot -proot -e 'FLUSH PRIVILEGES;'

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-interaction --ansi

      - name: Clear cache
        run: |
          php${{ matrix.php }} artisan optimize:clear --env=testing

      - name: Migrate and seed the database
        run: |
          php${{ matrix.php }} artisan migrate --force -n --env=testing --database=mysql_testing

      - name: Run PHP tests
        run: php${{ matrix.php }} artisan test --env=testing
